// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(robot) {
    var assigned, backUser, buildTurn, forwardTurn, forwardUser, userList;
    userList = ['taro', 'jiro', 'saburo'];
    assigned = robot.brain.get('assigned');
    if (assigned === null) {
      assigned = {
        turn: buildTurn(new Date('2014-08-01')),
        user: 0
      };
    }
    forwardUser = function() {
      assigned.user++;
      if (assigned.user >= userList.length) {
        return assigned.user = 0;
      }
    };
    backUser = function() {
      assigned.user--;
      if (assigned.user < 0) {
        return assigned.user = userList.length - 1;
      }
    };
    buildTurn = function(date) {
      return date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + date.getDay();
    };
    forwardTurn = function() {
      return assigned.turn;
    };
    robot.respond(/hoge$/i, function(msg) {
      return msg.send(userList[assigned.user]);
    });
    robot.respond(/skip$/i, function(msg) {
      forwardUser();
      return msg.send(userList[assigned.user]);
    });
    robot.respond(/back$/i, function(msg) {
      backUser();
      return msg.send(userList[assigned.user]);
    });
    robot.respond(/bset$/i, function(msg) {
      return robot.brain.set('assigned', assigned);
    });
    robot.respond(/bget$/i, function(msg) {
      return console.log(assigned);
    });
    return robot.respond(/assigned$/i, function(msg) {
      msg.send('assigned');
      return console.log(assigned);
    });
  };

}).call(this);
